package com.habitia.notifications.domain;

public enum NotificationType {
    REVIEW_RECEIVED,
    REVIEW_APPROVED,
    REVIEW_RESPONSE,
    MESSAGE_RECEIVED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED
}
